
- file: name=/opt/downloads state=directory mode=0775

- get_url: url=https://dl.bintray.com/mitchellh/packer/{{ packer_zip_filename }} dest=/opt/downloads/{{ packer_zip_filename }} mode=0444 sha256sum={{ packer_sha256sum }}

- file: name=/opt/packer state=directory mode=0755

- unarchive: src=/opt/downloads/{{ packer_zip_filename }} dest=/opt/packer creates=/opt/packer/packer

- get_url: url=https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_rpm_filename }} dest=/opt/downloads/{{vagrant_rpm_filename }} mode=0444 sha256sum={{ vagrant_sha256sum }}

- lineinfile: dest=/etc/profile.d/packer.sh state=present line="PATH={{ packer_path }}:$PATH" create=true

- yum: name=/opt/downloads/{{ vagrant_rpm_filename }} state=present

- get_url: url=http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo dest=/etc/yum.repos.d/virtualbox.repo mode=0440

- yum: name={{ virtualbox_version }} state=present