
# When setting the vars below swap is set to twice memory and taken from space inside disk_size so ensure you create the disk bigger
---
- hosts:
  - localhost
  gather_facts: False
  vars:
    build_version: 0.1
    vagrant_ssh_username: vagrant
    vagrant_ssh_password: vagrant
    vagrant_root_password: vagrant
    vagrant_ssh_public_key_url: https://raw.githubusercontent.com/pixie79/vagrant/master/keys/vagrant.pub
    vagrant_ssh_key_path: "{% raw %}{{user `home`}}{% endraw %}/.ssh/vagrant"
    vagrant_disk_size: 51200
    vagrant_memory: 4096
    vagrant_cpus: 2
    virtualbox_headless_mode: false
    s3_region: us-east-1
    s3_bucket: bdpimages
    s3_box_dir: vagrant/boxes
  roles:
  - centos-base-packer
